name: Deploy to VM

on:
  push:
    branches:
      - master  # or the branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Connect to VM and run commands
      run: |
        sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
          echo "Logged into the VM successfully."
          sudo apt update
          sudo apt install nginx -y
          sudo service nginx start
          
        EOF
